### ISSUE TITLE
Question help

### ISSUE THREAD

**Issue by PigCharid** [VedaOrg/Veda-docs#5]
I am a developer and have studied the Veda protocol. I have a question. How do you ensure that BVM will not go down? Is BVM centralized?

**Comment by Raylin51** [comment]
We will package Veda-ord, Veda-core, and Veda-bvm into a single Docker image, allowing anyone to access Veda data by running a Docker container.

**Comment by ubuygold** [comment]
Who will have the right to write data on chain, who will hold the bitcoins people deposit?

**Comment by Raylin51** [comment]
> Who will have the right to write data on chain, who will hold the bitcoins people deposit?

Everyone can write data on chain. The Bitcoin deposit wallet should be a multi-signature address held by multiple parties.

**Comment by Raylin51** [comment]
> ## Writing access
> I understand that everyone can write data on the chain, such as the raw data of a transaction or calldata similar to EVM. But after the veda-bvm processes a transaction, who should write the changes in the blockchain state? My understanding is that it should be done by the bvm or a wallet controlled by the official authorities; or is it that each user submits their transaction (and writes it after the bvm processes it and receives a receipt), but wouldn't this be risky and susceptible to attacks? Do you have any solutions for this?
> 
Currently, the state changes of veda-bvm can only be made through internal Rpc interface calls, which will be invoked by the data validator, veda-core. You can understand that in the initial phase, veda-bvm is a query interface program that anyone can run, and without any destructive changes, the computational results of veda-bvm will be fixed. In the future, we will incentivize the deployment of the veda program, encouraging more people in the network to participate in deploying veda.

**Comment by Raylin51** [comment]
> ## About multisig
> If the bitcoin deposited by users are controlled by a multi-signature wallet, does this mean that every time a user withdraws their deposit, it needs to go through multi-signature approval? (If this is the case) then this would be impossible with a large number of users. A bridge in other chains (I know veda is not a Layer2 of bitcoin and bridges don't exist in veda, but their function seems similar to me) is usually a smart contract that can be triggered, but a wallet can't be triggered.
> 

Currently, we have other teams attempting to deploy cross-chain bridges on veda (essentially for Bitcoin deposits and withdrawals). It's possible that some cryptographic application will be used to manage the actual BTC deposit and withdrawal wallet's private key on another chain, utilizing some cryptographic principle. Withdrawal requests would then be sent through a certain type of message transmission to the program or smart contract on the other chain that controls the BTC wallet's private key. There is no concrete plan yet, but I am very pleased that you are interested in this matter.

**Comment by ubuygold** [comment]
Thank you for reply. Will you launch a testnet soon... It is too expensive to deploy a test contract on Veda now....

**Comment by Raylin51** [comment]
> Thank you for reply. Will you launch a testnet soon... It is too expensive to deploy a test contract on Veda now....

We will open-source bvm in a few days, allowing developers to run a bvm locally. Using the internal Rpc of bvm, you can transmit contract bytecode and calldata to test your contract.
